blog/web/views.py
from flask import Blueprint, render_template

from back.models import Article, ArticleType

web_blue = Blueprint('web', __name__)

@web_blue.route('/index/')
def index():
    articles = Article.query.order_by(Article.create_time).all()
    # atypes = ArticleType.query.all()
    # # 统计每个分类有多少篇文章
    # results = {}
    # for atype in atypes:
    #     num = Article.query.filter(atype.id == Article.type).count()
    #     if num == 0:
    #         continue
    #     results[atype.t_name] = num
    return render_template('web/index.html', articles=articles)


@web_blue.route('/category/<category_name>')
def category(category_name):
    atype = ArticleType.query.filter(ArticleType.t_name == category_name).first()
    articles= Article.query.filter(Article.type == atype.id).all()
    return render_template('web/category.html', articles=articles)


@web_blue.route('/info/<int:id>/')
def info(id):
    article = Article.query.get(id)
    articles = Article.query.order_by(Article.create_time).all()
    index = articles.index(article)
    length = len(articles) - 1

    if index == 0:
        pre_art = {}
    else:
        pre_art = articles[index-1]

    if index == length :
        next_art = {}
    else:
        next_art = articles[index+1]
    return render_template('web/info.html', article=article, pre_art=pre_art, next_art=next_art)


@web_blue.route('/art_list/')
def art_list():
    # 首页按发布时间显示文章
    articles = Article.query.order_by(Article.create_time).all()
    return render_template('web/art_list.html', articles=articles)

blog/templates/web/about.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="css/base.css" rel="stylesheet">
<link href="css/index.css" rel="stylesheet">
<link href="css/m.css" rel="stylesheet">
<script src="js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="js/hc-sticky.js"></script>
<script type="text/javascript" src="js/comm.js"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">杨青个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="index.html">网站首页</a></li>
      <li><a href="share.html">我的相册</a></li>
      <li><a href="list.html">我的日记</a></li>
      <li><a href="about.html">关于我</a></li>
      <li><a href="gbook.html">留言</a></li>
      <li><a href="info.html">内容页</a></li>
      <li><a href="infopic.html">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
    <div class="about_me">
      <h2>关于我</h2>
      <ul>
        <i><img src="images/4.jpg"></i>
        <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
      </ul>
    </div>
    <div class="wdxc">
      <h2>我的相册</h2>
      <ul>
        <li><a href="/"><img src="images/7.jpg"></a></li>
        <li><a href="/"><img src="images/8.jpg"></a></li>
        <li><a href="/"><img src="images/9.jpg"></a></li>
        <li><a href="/"><img src="images/10.jpg"></a></li>
        <li><a href="/"><img src="images/11.jpg"></a></li>
        <li><a href="/"><img src="images/12.jpg"></a></li>
      </ul>
    </div>
    <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
      <ul>
        <li><a href="/">学无止境（33）</a></li>
        <li><a href="/">日记（19）</a></li>
        <li><a href="/">慢生活（520）</a></li>
        <li><a href="/">美文欣赏（40）</a></li>
      </ul>
    </div>
   
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="images/wx.jpg">
      </ul>
    </div>
  </aside>
  <main class="r_box">
     <div class="about">
      <p>杨青，女，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。我入行早，大家也亲切的叫我&ldquo;青姐&rdquo;。<br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
          <h2>About my blog</h2>
          &nbsp;
          <p>域 名：www.yangqq.com 创建于2011年01月12日&nbsp;</p>
          <br />
          <p>服务器：阿里云服务器&nbsp;&nbsp;<a href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm" target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>
          <br />
          <p>备案号：蜀ICP备11002373号-1</p>
          <br />
          <p>程 序：PHP 帝国CMS7.5</p>
  
     </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

blog/templates/web/art_list.html
{% extends 'web/base_main.html' %}

{% block title %}
  首页_陈伦巨个人博客
{% endblock %}

{% block js %}
  {{ super() }}

{% endblock %}


{% block content %}
  <main class="r_box">
    {% for article in articles %}
      <div class="well">
        <h1><a href="{{ url_for('web.info', id=article.id) }}">{{ article.title }}</a></h1>
        <p>{{ article.desc }}</p>
      </div>
    {% endfor %}
  </main>
{% endblock %}

blog/templates/web/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="个人博客,陈伦巨个人博客,陈伦巨" />
    <meta name="description" content="陈伦巨个人博客" />
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}


</head>
<body>
    {% block header %}
    {% endblock %}

    <a href="#" class="cd-top">Top</a>
    <article>
        {% block aside %}
        {% endblock %}

        {% block content %}
        {% endblock %}
    </article>

    {% block footer %}
    {% endblock %}
    <a href="#" class="cd-top">Top</a>

    {% block js %}
    {% endblock %}
</body>
</html>

blog/templates/web/base_main.html
{% extends 'web/base.html' %}

{% block css %}
    <link href="/static/web/css/base.css" rel="stylesheet">
    <link href="/static/web/css/blog.css" rel="stylesheet">
    <link href="/static/web/css/index.css" rel="stylesheet">
    <link href="/static/web/css/m.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="../../dist/css/bootstrap-theme.min.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="theme.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
{% endblock %}

{% block js %}
    <script src="/static/web/js/modernizr.js"></script>
    <script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/web/js/comm.js"></script>
    
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
{% endblock %}

{% block header %}
    <header class="header-navigation" id="header">
      <nav><div class="logo"><a href="/">陈伦巨个人博客</a></div>
        <h2 id="mnavh"><span class="navicon"></span></h2>
        <ul id="starlist">
          <li><a href="{{ url_for('web.index') }}">网站首页</a></li>
          <li><a href="{{ url_for('web.art_list') }}">我的笔记</a></li>
          <li><a href="about.html">关于我</a></li>
        </ul>
    </nav>
    </header>
{% endblock %}

{% block aside %}
    <aside class="l_box">

        <div class="panel panel-primary about_me" style="margin-bottom:40px">
            <div class="panel-heading">
              <h3 class="panel-title">关于我</h3>
            </div>
            <div class="panel-body ">
                <i><img src="/static/web/images/4.jpg"></i>
                <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
            </div>
        </div>

      <!--<div class="search">-->
        <!--<form action="/e/search/index.php" method="post" name="searchform" id="searchform">-->
          <!--<input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">-->
          <!--<input name="show" value="title" type="hidden">-->
          <!--<input name="tempid" value="1" type="hidden">-->
          <!--<input name="tbname" value="news" type="hidden">-->
          <!--<input name="Submit" class="input_submit" value="搜索" type="submit">-->
        <!--</form>-->
      <!--</div>-->

      <div class="fenlei">
        <div class="list-group">
          <a href="#" class="list-group-item active">文章分类</a>
          {% for key in articles|category %}
            <a href="{{ url_for('web.category', category_name=key) }}" class="list-group-item">{{ key }}（{{(articles|category)[key]}}）</a>
          {% endfor %}
        </div>
      </div>



    <div class="fenlei">
    <div class="list-group">
        <a href="" class="list-group-item active">
          友情链接
        </a>
        <a href="https://github.com/" class="list-group-item">github</a>
        <a href="https://www.csdn.net/" class="list-group-item">CSDN</a>
        <a href="https://www.jianshu.com/" class="list-group-item">简书</a>
        <a href="https://gitee.com/" class="list-group-item">gitee</a>
    </div>
    </div>


      <div class="panel panel-primary guanzhu">
        <div class="panel-heading">
          <h3 class="panel-title">关注我</h3>
        </div>
        <div class="panel-body">
          <img src="/static/web/images/wx.jpg">
        </div>
       </div>


    </aside>
{% endblock %}

{% block footer %}
    <footer>
      <p>Design by <a href="http://www.yangqq.com" target="_blank">陈伦巨个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
    </footer>
{% endblock %}

blog/templates/web/category.html
{% extends 'web/base_main.html' %}

{% block title %}
  博客分类页面
{% endblock %}

{% block js %}
  {{ super() }}
  <script src="/static/web/js/modernizr.js"></script>
{% endblock %}


{% block content %}
  <main class="r_box">
    {% for article in articles %}
      <div class="well">
        <h1><a href="{{ url_for('web.info', id=article.id) }}">{{ article.title }}</a></h1>
        <p>{{ article.desc }}</p>
      </div>
    {% endfor %}
  </main>
{% endblock %}

blog/templates/web/gbook.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="css/base.css" rel="stylesheet">
<link href="css/index.css" rel="stylesheet">
<link href="css/m.css" rel="stylesheet">
<script src="js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="js/hc-sticky.js"></script>
<script type="text/javascript" src="js/comm.js"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">杨青个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="index.html">网站首页</a></li>
      <li><a href="share.html">我的相册</a></li>
      <li><a href="list.html">我的日记</a></li>
      <li><a href="about.html">关于我</a></li>
      <li><a href="gbook.html">留言</a></li>
      <li><a href="info.html">内容页</a></li>
      <li><a href="infopic.html">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
    <div class="about_me">
      <h2>关于我</h2>
      <ul>
        <i><img src="images/4.jpg"></i>
        <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
      </ul>
    </div>
    <div class="wdxc">
      <h2>我的相册</h2>
      <ul>
        <li><a href="/"><img src="images/7.jpg"></a></li>
        <li><a href="/"><img src="images/8.jpg"></a></li>
        <li><a href="/"><img src="images/9.jpg"></a></li>
        <li><a href="/"><img src="images/10.jpg"></a></li>
        <li><a href="/"><img src="images/11.jpg"></a></li>
        <li><a href="/"><img src="images/12.jpg"></a></li>
      </ul>
    </div>
     <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
      <ul>
        <li><a href="/">学无止境（33）</a></li>
        <li><a href="/">日记（19）</a></li>
        <li><a href="/">慢生活（520）</a></li>
        <li><a href="/">美文欣赏（40）</a></li>
      </ul>
    </div>
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="images/wx.jpg">
      </ul>
    </div>
  </aside>
  <main class="r_box">
<div class="gbook">
      <div class="fb">
        <ul>
          <p class="fbtime"><span> 2018-07-21 </span> 夜月归途</p>
          <p class="fbinfo">从青姐朋友圈分享的文章《我为什么要做个人网站》过来的，自习看了下你的网站非常不错，看的出来你一直在坚持!</p>
        </ul>
      </div>
      <div class="hf">
        <ul>
          <p class="zzhf"><font color="#FF0000">站长回复:</font>感谢捧场啊！看了你的网站，有两个月没更新了哦~</p>
        </ul>
      </div>
      <div class="fb">
        <ul>
          <p class="fbtime"><span> 2018-07-10 </span> 周宏</p>
          <p class="fbinfo">读《从今日起，我永久卸载今日头条》有感。正如作者所说，这个APP抓住了很多人性的特点，在简单、重复、爽这三点上做到了极致。但是我认为永久卸载这个想法比较荒诞，任何东西你只要有自控力，就能将它为我所用。曾经一度我也是刷头条根本停不下来</p>
        </ul>
      </div>
      <div class="hf">
        <ul>
          <p class="zzhf"><font color="#FF0000">站长回复:</font>嗯，我也是自制力有限，删除头条就是矫枉过正而已，这个因人而异，不强求他人，也不想标题党。</p>
        </ul>
      </div>
      <div class="fb">
        <ul>
          <p class="fbtime"><span> 2018-07-09 </span> 文颖</p>
          <p class="fbinfo">加油吖</p>
        </ul>
      </div>
      <div class="hf">
        <ul>
          <p class="zzhf"><font color="#FF0000">站长回复:</font>感谢第一条留言的支持！：）</p>
        </ul>
      </div>
      <div class="gbox">
        <form action="../../enews/index.php" method="post" name="form1" id="form1">
          <p> <strong>来说点儿什么吧...</strong></p>
          <p><span> 您的姓名:</span>
            <input name="name" type="text" id="name">
            *</p>
          <p><span>联系邮箱:</span>
            <input name="email" type="text" id="email">
            *</p>
          <p><span class="tnr">留言内容:</span>
            <textarea name="lytext" cols="60" rows="12" id="lytext"></textarea>
          </p>
          <p>
            <input type="submit" name="Submit3" value="提交">
            <input name="enews" type="hidden" id="enews" value="AddGbook">
          </p>
        </form>
      </div>
    </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

blog/templates/web/index.html
{% extends 'web/base_main.html' %}

{% block title %}
  首页_陈伦巨个人博客
{% endblock %}

{% block js %}
  {{ super() }}
  <script src="/static/web/js/modernizr.js"></script>
{% endblock %}


{% block content %}
  <main class="r_box">
    {% for article in articles %}
      <div class="well">
        <h1><a href="{{ url_for('web.info', id=article.id) }}">{{ article.title }}</a></h1>
        <p>{{ article.desc }}</p>
      </div>
    {% endfor %}
  </main>
{% endblock %}

blog/templates/web/info.html
{% extends 'web/base_main.html' %}

{% block title %}
首页_陈伦巨个人博客
{% endblock %}

{% block css %}
{{ super() }}
<link href="/static/web/css/jquery.fancybox.css">
<link href="/static/web/css/info.css" rel="stylesheet">
{% endblock %}

{% block js %}
{{ super() }}
<script src="/static/mdeditor/js/jquery.min.js"></script>
<script src="/static/mdeditor/lib/marked.min.js"></script>
<script src="/static/mdeditor/lib/prettify.min.js"></script>
<script src="/static/mdeditor/lib/raphael.min.js"></script>
<script src="/static/mdeditor/lib/underscore.min.js"></script>
<script src="/static/mdeditor/lib/sequence-diagram.min.js"></script>
<script src="/static/mdeditor/lib/flowchart.min.js"></script>
<script src="/static/mdeditor/lib/jquery.flowchart.min.js"></script>
<script src="/static/mdeditor/js/editormd.min.js"></script>

<script type="text/javascript">
  var testEditor;
  $(function () {
    testEditor = editormd.markdownToHTML("doc-content", {//注意：这里是上面DIV的id
      htmlDecode: "style,script,iframe",
      emoji: true,
      taskList: true,
      tex: true, // 默认不解析
      flowChart: true, // 默认不解析
      sequenceDiagram: true, // 默认不解析
      codeFold: true,
    });
  });
</script>
{% endblock %}




{% block content %}
<main>
  <div class="infosbox">
    <!--<div class="newsview">-->
    <!--<h1 class="blog-post-title">{{article.title}}</h1>-->
    <!--<div class="bloginfo">-->
    <!--<ul>-->
    <!--<li class="author">作者：<a href="/">杨青</a></li>-->
    <!--<li class="lmname"><a href="/">{{ article.tp.t_name }}</a></li>-->
    <!--<li class="timer">时间：{{ article.create_time }}</li>-->
    <!--</ul>-->
    <!--</div>-->
    <!--</div>-->


    <!--<div class="tags"><a href="/" target="_blank">个人博客</a> &nbsp; <a href="/" target="_blank">小世界</a></div>-->
    <!--<p class="lead blog-description">{{ article.desc }}</p>-->
    <!--<div class="news_about"><strong>简介</strong>{{ article.desc }}</div>-->

    <div class="blog-header">
      <h1 class="blog-title">{{article.title}}</h1>
      <p class="lead blog-description">{{ article.desc }}</p>
    </div>

    <div class="blog-main">
      <p class="blog-post-meta">{{ article.create_time }} by 陈伦巨</p>
      <hr>

      <div id="doc-content">
        <textarea style="display:none;">{{ article.content | safe }}</textarea>
      </div>

    </div>


    <div style="text-align:center;color: #ccc;font-size:14px;" class="">-------------本文结束<i class="fa fa-paw"></i>感谢您的阅读-------------</div>


    <div>
      <div id='reward'>
        <div>如果这篇文章对您的工作和学习有所帮助，希望您能支持一下我，这就是鼓励我写作的动力。</div>
        <button id="rewardButton" disable="enable"
          onclick="var qr = document.getElementById('QR'); if (qr.style.display === 'none') {qr.style.display='block';} else {qr.style.display='none'}">
          <span>打赏</span>
        </button>
        <div id="QR" style="display: none;">


          <div id="wechat" style="display: inline-block">
            <a href="/static/web/images/wechatpay.jpg" class="fancybox fancybox.image" rel="group"><img id="wechat_qr"
                src="/static/web/images/wechatpay.jpg" alt="刚好遇见拖拉机 微信支付"></a>
            <p>微信支付</p>
          </div>



          <div id="alipay" style="display: inline-block">
            <a href="/static/web/images/alipay.jpg" class="fancybox fancybox.image" rel="group"><img id="alipay_qr"
                src="/static/web/images/alipay.jpg" alt="刚好遇见拖拉机 支付宝"></a>
            <p>支付宝</p>
          </div>




        </div>
      </div>

    </div>




    <div class="nextinfo">
      {% if pre_art %}
      <p>上一篇：<a href="{{ url_for('web.info', id=pre_art.id) }}">{{ pre_art.title }}</a></p>
      {% endif %}
      {% if next_art %}
      <p>下一篇：<a href="{{ url_for('web.info', id=next_art.id) }}">{{ next_art.title }}</a></p>
      {% endif %}
    </div>


    <div class="news_pl">
      <h2>文章评论</h2>
      <!-- 来必力City版安装代码 -->
      <div id="lv-container" data-id="city" data-uid="MTAyMC80Mjg5NS8xOTQ0MQ==">
        <script type="text/javascript">
          (function (d, s) {
            var j, e = d.getElementsByTagName(s)[0];

            if (typeof LivereTower === 'function') { return; }

            j = d.createElement(s);
            j.src = 'https://cdn-city.livere.com/js/embed.dist.js';
            j.async = true;

            e.parentNode.insertBefore(j, e);
          })(document, 'script');
        </script>
        <noscript>为正常使用来必力评论功能请激活JavaScript</noscript>
      </div>
      <!-- City版安装代码已完成 -->
    </div>

  </div>
</main>
{% endblock %}