blog/back/models.py
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(10), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    is_delete = db.Column(db.Boolean, default=0)
    create_time = db.Column(db.DateTime, default=datetime.now())
    last_login_time = db.Column(db.DateTime, default=datetime.now())
    current_login_time = db.Column(db.DateTime, default=datetime.now())

    __tablename__ = 'user'

    def save(self):
        db.session.add(self)
        db.session.commit()


class ArticleType(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    t_name = db.Column(db.String(10), unique=True, nullable=False)
    arts = db.relationship('Article', backref=db.backref('tp'))

    __tablename__ = 'art_type'

    def save(self):
        db.session.add(self)
        db.session.commit()


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(30), nullable=False)
    desc = db.Column(db.String(150), nullable=False)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now())
    type = db.Column(db.Integer, db.ForeignKey('art_type.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

blog/back/views.py
from datetime import datetime
from math import ceil

from flask import Blueprint, render_template, request, redirect, url_for, session
from werkzeug.security import generate_password_hash,check_password_hash

from back.models import User, Article, ArticleType, db
from utils.functions import is_login

back_blue = Blueprint('back', __name__)

ITEMS_PER_PAGE = 10

@back_blue.route('/index/')
@is_login
def index():
    return render_template('back/index.html')





@back_blue.route('/register/', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('back/register.html')
    if request.method == 'POST':
        # 获取数据
        username = request.form.get('username')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        if not all([username, password, password2]):
            error = '请提交完整的信息！'
            return render_template('back/register.html', error=error)
        user = User.query.filter(User.username == username).first()
        if user:
            error = '改账号已注册，请更换账号！'
            return render_template('back/register.html', error=error)
        if password != password2:
            error = '两次密码不一致！'
            return render_template('back/register.html', error=error)

        # 成功注册
        user = User()
        user.username = username
        print(username)
        user.password = generate_password_hash(password)
        user.save()
        return redirect(url_for('back.login'))


@back_blue.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('back/login.html')

    if request.method == 'POST':
        # 获取数据
        username = request.form.get('username')
        password = request.form.get('password')
        if not all([username, password]):
            error = '请填写完整信息！'
            return render_template('back/login.html', error=error)
        user = User.query.filter(User.username == username).first()
        if not user:
            error = '改用户未注册！'
            return render_template('back/login.html', error=error)
        if not check_password_hash(user.password, password):
            error = '密码错误，请修改密码！'
            return render_template('back/login.html', error=error)
        # 登录成功,保存标识符，跳转首页
        # session['user'] = user
        session['user_id'] = user.id
        session.permanent = True
        user.current_login_time = datetime.now()
        user.save()

        return redirect(url_for('back.index'))


@back_blue.route('/logout/', methods=['GET'])
@is_login
def logout():
    user = User.query.filter(User.id == session['user_id']).first()
    user.last_login_time = user.current_login_time
    user.current_login_time = None
    user.save()
    del session['user_id']
    return redirect(url_for('back.login'))


@back_blue.route('/a_type/', methods=['GET', 'POST'])
@is_login
def a_type():
    if request.method == 'GET':
        types = ArticleType.query.all()
        return render_template('back/category_list.html', types=types)


@back_blue.route('/add_type/', methods=['GET', 'POST'])
@is_login
def add_type():
    if request.method == 'GET':
        return render_template('back/category_add.html')
    if request.method == 'POST':
        atype = request.form.get('atype')
        if atype:
            # 保存分类
            art_type = ArticleType()
            art_type.t_name = atype
            art_type.save()
            return redirect(url_for('back.a_type'))
        else:
            error = '请填写分类信息！'
            return render_template('back/category_add.html', error=error)


@back_blue.route('/del_type/<int:id>/', methods=['GET'])
@is_login
def del_type(id):
    # 删除分类
    atype = ArticleType.query.get(id)
    db.session.delete(atype)
    db.session.commit()
    return redirect(url_for('back.a_type'))


@back_blue.route('/article_list/', methods=['GET'])
@is_login
def article_list():
    articles = Article.query.all()
    art_total = len(articles)
    pages = ceil(art_total / ITEMS_PER_PAGE)
    return render_template('back/article_list.html', articles=articles, pages=pages)



@ back_blue.route('/article_page/<int:page>',methods=['GET'])
@ is_login
def article_page(page):
    articles = Article.query.all()
    art_total = len(articles)
    pages = ceil(art_total / ITEMS_PER_PAGE)
    articles = articles[(page - 1) * ITEMS_PER_PAGE:page * ITEMS_PER_PAGE]
    return render_template('back/article_list.html', articles=articles, pages=pages, page=page)



@back_blue.route('/article_add/', methods=['GET', 'POST'])
@is_login
def article_add():
    if request.method == 'GET':
        types = ArticleType.query.all()
        return render_template('back/article_add.html', types=types)
    if request.method == 'POST':
        # 获取数据
        title = request.form.get('name')
        desc = request.form.get('desc')
        category = request.form.get('category')
        content = request.form.get('my-editormd-html-code')
        content2 = request.form.get('my-editormd-markdown-doc')
        print(content)
        print(content2)

        if not all([title, desc, category, content]):
            error = '请填写完整信息！'
            return render_template('back/article_add.html', error=error)
        # 保存到数据库
        art = Article()
        art.title = title
        art.desc = desc
        art.type = category
        art.content = content
        art.save()
        return redirect(url_for('back.article_page', page=1))


@back_blue.route('/user_info/', methods=['GET', 'POST'])
@is_login
def user_info():
    if request.method == 'GET':
        user = User.query.filter(session['user_id'] == User.id).first()
        username = user.username
        create_time = user.create_time
        last_login_time = user.last_login_time
        current_login_time = user.current_login_time
        return render_template('back/user_info.html',
                               username=username,
                               create_time=create_time,
                               last_login_time=last_login_time,
                               current_login_time=current_login_time)
    if request.method == 'POST':
        return logout()



@back_blue.route('/del_art/<int:id>/', methods=['GET'])
@is_login
def del_art(id):
    # 删除分类
    art = Article.query.get(id)
    db.session.delete(art)
    db.session.commit()
    return redirect(url_for('back.article_page', page=1))


@back_blue.route('/art_modify/<int:id>/', methods=['GET', 'POST'])
@is_login
def art_modify(id):
    art = Article.query.get(id)
    types = ArticleType.query.all()
    if request.method == 'GET':
        return render_template('back/article_modify.html', art=art, types=types)
        # 修改文章前显示原文本信息
    if request.method == 'POST':
        # 修改文章后重新获取数据，保存到数据库
        title = request.form.get('name')
        desc = request.form.get('desc')
        category = request.form.get('category')
        content = request.form.get('content')

        art.title = title
        art.desc = desc
        art.type = category
        art.content = content
        art.save()
        return redirect(url_for('back.article_page', page=1))

blog/web/views.py
from flask import Blueprint, render_template

from back.models import Article, ArticleType

web_blue = Blueprint('web', __name__)

@web_blue.route('/index/')
def index():
    articles = Article.query.order_by(Article.create_time).all()
    # atypes = ArticleType.query.all()
    # # 统计每个分类有多少篇文章
    # results = {}
    # for atype in atypes:
    #     num = Article.query.filter(atype.id == Article.type).count()
    #     if num == 0:
    #         continue
    #     results[atype.t_name] = num
    return render_template('web/index.html', articles=articles)


@web_blue.route('/category/<category_name>')
def category(category_name):
    atype = ArticleType.query.filter(ArticleType.t_name == category_name).first()
    articles= Article.query.filter(Article.type == atype.id).all()
    return render_template('web/category.html', articles=articles)


@web_blue.route('/info/<int:id>/')
def info(id):
    article = Article.query.get(id)
    articles = Article.query.order_by(Article.create_time).all()
    index = articles.index(article)
    length = len(articles) - 1

    if index == 0:
        pre_art = {}
    else:
        pre_art = articles[index-1]

    if index == length :
        next_art = {}
    else:
        next_art = articles[index+1]
    return render_template('web/info.html', article=article, pre_art=pre_art, next_art=next_art)


@web_blue.route('/art_list/')
def art_list():
    # 首页按发布时间显示文章
    articles = Article.query.order_by(Article.create_time).all()
    return render_template('web/art_list.html', articles=articles)

blog/templates/back/article_add.html
{% extends 'back/base_main.html' %}

{% block title %}
    文章添加
{% endblock %}

 {% block js %}
    {{ super() }}
    <script type="text/javascript">
      $(function() {
          editormd("my-editormd", {//注意1：这里的就是上面的DIV的id属性值
              width   : "90%",
              height  : 400,
              syncScrolling : "single",
              path    : "/static/mdeditor/lib/",//注意2：你的路径
              saveHTMLToTextarea : false//注意3：这个配置，方便post提交表单
          });
      });
    </script>

 {% endblock %}

    
{% block content %}
<section class="rt_wrap mCustomScrollbar">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">添加文章</h2>
            <a class="fr top_rt_btn" href="/back/article_page/1">返回文章列表</a>
        </div>
        <form action="" method="post">
            <input type='hidden' name='csrfmiddlewaretoken' value='q3tTrBuDcMhfvSS9x2u0yQAyRbboSQuyMyt42kgwgKS0rKxCv31hIWTsS3ULhZn7' />
            <section>
                
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name"  style="width:120px;">文章标题：</span>
                        <input type="text" name="name" value="" class="textbox textbox_295" />
                        
                    </li>
                    <li>
                        <span class="item_name"  style="width:120px;">文章描述：</span>
                        <input type="text" name="desc" value=""  class="textbox textbox_295" />
                        
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">分类：</span>
                        <select class="select" name="category">
                                {% for type in types %}
                                    <option value="{{ type.id }}">{{ type.t_name }}</option>
                                {% endfor %}
                        </select>
                        
                    </li>


                    <li>
                        <span class="item_name" style="width:120px;">文章内容：</span>

                        <div id="my-editormd" style="width: 90%; height: auto;">
                        <textarea id="my-editormd-markdown-doc" name="my-editormd-markdown-doc" style="display:none;"></textarea>
                        <!-- 注意：name属性的值-->
                        <textarea id="my-editormd-html-code" name="my-editormd-html-code" style="display:none;"></textarea>
                        </div>

                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" value='保存提交' class="link_btn"/>
                        {{ error }}
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>
{% endblock %}

blog/templates/back/article_list.html
{% extends 'back/base_main.html' %}

{% block title %}
    文章列表
{% endblock %}

{% block content %}
<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章列表</h2>
            <a href="{{ url_for('back.article_add') }}" class="fr top_rt_btn add_icon">添加文章</a>
        </div>
        <table class="table">
            <tr>
                <th>文章标题</th>
                <th>分类</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
                {% for article in articles %}
                    <tr>
                        <td class="center">{{ article.title }}</td>
                        <td class="center">{{ article.tp.t_name }}</td>
                        <td class="center">{{ article.create_time }}</td>
                        <td class="center">
                            <a href="{{ url_for('back.art_modify', id=article.id) }}" title="编辑" class="link_icon">&#101;</a>
                            <a href="{{ url_for('back.del_art', id=article.id) }}" title="删除" class="link_icon">&#100;</a>
                        </td>
                    </tr>
                {% endfor %}
        </table>
        <aside class="paging">
            <a>当前{{ page }}页</a>
            <a href="{{ url_for('back.article_page', page=1) }}">第一页</a>
                {% if page >= 3 %}
                ...
                {% endif %}
                {% for page in range(page-1, page+2) %}
                    {% if 1<=page<=pages %}
                        <a href="{{ url_for('back.article_page', page=page) }}"> {{ page }} </a>
                    {% endif %}

                {% endfor %}
                {% if page <= pages-2 %}
                ...
                {% endif %}
            <a href="{{ url_for('back.article_page', page=pages) }}">最后一页</a>
        </aside>
    </div>
</section>
{% endblock %}

blog/templates/back/article_modify.html
{% extends 'back/base_main.html' %}

{% block title %}
    修改文章
{% endblock %}

 {% block js %}
    {{ super() }}

    <script type="text/javascript">
      $(function() {
          editormd("my-editormd", {//注意1：这里的就是上面的DIV的id属性值
              width   : "90%",
              height  : 400,
              syncScrolling : "single",
              path    : "/static/mdeditor/lib/",//注意2：你的路径
              saveHTMLToTextarea : false//注意3：这个配置，方便post提交表单
          });
      });
    </script>
 {% endblock %}

    
{% block content %}
<section class="rt_wrap mCustomScrollbar">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">商品详情</h2>
            <a class="fr top_rt_btn" href="/goods/goods_list/">返回商品列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <input type='hidden' name='csrfmiddlewaretoken' value='q3tTrBuDcMhfvSS9x2u0yQAyRbboSQuyMyt42kgwgKS0rKxCv31hIWTsS3ULhZn7' />
            <section>
                
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name"  style="width:120px;">文章标题：</span>
                        <input type="text" name="name" value="{{ art.title }}" class="textbox textbox_295" placeholder="文章标题"/>
                        
                    </li>
                    <li>
                        <span class="item_name"  style="width:120px;">文章描述：</span>
                        <input type="text" name="desc" value="{{ art.desc }}"  class="textbox" placeholder="文章描述"/>
                        
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">分类：</span>
                        <select class="select" name="category">
                                {% for type in types %}
                                    <option value="{{ type.id }}" {% if art.type == type.id %} selected = 'selected' {% endif %}>{{ type.t_name }}</option>
                                    <!--<option value="{{ type.id }}" >{{ type.t_name }}</option>-->
                                {% endfor %}
                        </select>
                        
                    </li>


                    <li>

                        <div id="my-editormd" style="width: 90%; height: auto;">
                        <textarea id="my-editormd-markdown-doc" name="my-editormd-markdown-doc" style="display:none;">{{ art.content | safe }}</textarea>
                        <!-- 注意：name属性的值-->
                        <textarea id="my-editormd-html-code" name="my-editormd-html-code" style="display:none;"></textarea>
                        </div>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" value='保存提交' class="link_btn"/>
                        {{ error }}
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>
{% endblock %}

blog/templates/back/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}


</head>
<body>
    {% block header %}
    {% endblock %}

    {% block aside %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</body>
</html>

blog/templates/back/base_main.html
{% extends 'back/base.html' %}

{% block css %}
    <link rel="stylesheet"href="/static/mdeditor/css/editormd.css" />
    <link rel="stylesheet" type="text/css" href="/static/back/css/style.css">
    <!--<link rel="stylesheet"  href="{{ url_for('static', filename='css/style.css') }}">-->

{% endblock %}

{% block js %}
    <script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
    <script src="/static/mdeditor/js/editormd.min.js"></script>
    <script src="/static/mdeditor/js/jquery.min.js"></script>


    <script src="/static/back/js/jquery.mCustomScrollbar.concat.min.js"></script>

{% endblock %}

{% block header %}
<header>
    <h1><img src="/static/back/images/admin_logo.png"/></h1>
    <h1  id="welcome_user"> 欢迎 {{ session | get_username }}! </h1>
    <ul class="rt_nav">
        <li><a href="{{ url_for('web.index') }}" target="_blank" class="website_icon">博客首页</a></li>
        <li><a href="#" class="set_icon">账号设置</a></li>
        <li><a href="{{ url_for('back.logout') }}" class="quit_icon">安全退出</a></li>
    </ul>
</header>

{% endblock %}

{% block aside %}
<aside class="lt_aside_nav content mCustomScrollbar">
    <h2><a href="{{ url_for('back.index') }}">博客后台管理系统</a></h2>
    <ul>
        <li>
            <dl>
                <dt>文章管理</dt>
                <!--当前链接则添加class:active-->
                <dd><a href="{{ url_for('back.a_type') }}">文章分类</a></dd>
                <dd><a href="{{ url_for('back.article_page', page=1) }}">文章列表</a></dd>
            </dl>
        </li>

        <li>
                <dl>
                    <dt>用户管理</dt>
                    <dd><a href="{{url_for('back.user_info') }}">用户信息</a></dd>
                </dl>
            </li>
    </ul>
</aside>

{% endblock %}

blog/templates/back/category_add.html
{% extends 'back/base_main.html' %}

{% block title %}
    添加文章分类
{% endblock %}


{% block content %}

<section class="rt_wrap mCustomScrollbar">
    
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章分类详情</h2>
            <a class="fr top_rt_btn" href="goods_category_list.html">返回文章分类列表</a>
        </div>
        <form action="" method="post">
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">分类名称：</span>
                         <input type="text" name='atype'>
                    </li>
                    
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>{{ error }}
                    </li>

                </ul>
            </section>
        </form>
    </div>
</section>
{% endblock %}

blog/templates/back/category_list.html
{% extends 'back/base_main.html' %}

{% block title %}
    文章分类
{% endblock %}


{% block content %}
<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章分类列表</h2>
            <a href="{{ url_for('back.add_type') }}" class="fr top_rt_btn add_icon">添加文章分类</a>
        </div>
        <table class="table">
            <tr>
                <th>文章分类类型</th>
                <th>文章分类删除</th>
            </tr>
        
            {% for type in types %}
            <tr>
                <td class="center">
                    {{ type.t_name }}
                </td>

                <td class="center">
                    <a href="{{ url_for('back.del_type', id=type.id) }}" title="删除分类" class="link_icon">&#101;</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</section>
{% endblock %}

blog/templates/back/goods_desc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>

    </title>
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <script src="js/jquery.js"></script>
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>

    
    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                    uploadJson:'/util/upload/kindeditor'
                });
        });
    </script>

</head>
<body>


<header>
    <h1><img src="images/admin_logo.png"/></h1>
    <ul class="rt_nav">
        <li><a href="/" target="_blank" class="website_icon">站点首页</a></li>
        <li><a href="#" class="set_icon">账号设置</a></li>
        <li><a href="login.html" class="quit_icon">安全退出</a></li>
    </ul>
</header>




    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">商城后台菜单栏</a></h2>
         <ul>
            <li>
                <dl>
                    <dt>商品管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="goods_category_list.html">商品分类</a></dd>
                    <dd><a href="goods_list.html">商品列表</a></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>订单管理</dt>
                    <dd><a href="order_list.html">订单列表</a></dd>
                </dl>
            </li>
            <li>    
                <dl>
                    <dt>用户管理</dt>
                    <dd><a href="user_list.html">用户列表</a></dd>
                </dl>
            </li>
            </ul>
    </aside>

    <style>
    .dataStatistic{width:400px;height:200px;border:1px solid #ccc;margin:0 auto;margin:10px;overflow:hidden}
    #cylindrical{width:400px;height:200px;margin-top:-15px}
    #line{width:400px;height:200px;margin-top:-15px}
    #pie{width:400px;height:200px;margin-top:-15px}
    </style>



<section class="rt_wrap">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">商品详情</h2>
            <a class="fr top_rt_btn" href="/goods/goods_list/">返回商品列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <input type='hidden' name='csrfmiddlewaretoken' value='QuPi2QUuEhlKchGijsQULGJKUZO6bOJacZPtDzGnIfWv89lLhtnbVM2EVRxtAXCJ' />
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">产品详情：</span>
                        <label style="display:inline-block;padding:15px;background:#f8f8f8;">
                            <textarea id="editor_id" name="content" style="width:700px;"></textarea>
                        </label>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>



</body>
</html>

blog/templates/back/index.html
{% extends '/back/base_main.html' %}

{% block title %}
    博客后台管理系统首页
{% endblock %}

{% block js %}
{{ super() }}
    <script src="/static/back/js/html5.js"></script>
    <script>
        (function ($) {
            $(window).load(function () {

                $("a[rel='load-content']").click(function (e) {
                    e.preventDefault();
                    var url = $(this).attr("href");
                    $.get(url, function (data) {
                        $(".content .mCSB_container").append(data); //load new content inside .mCSB_container
                        //scroll-to appended content 
                        $(".content").mCustomScrollbar("scrollTo", "h2:last");
                    });
                });

                $(".content").delegate("a[href='top']", "click", function (e) {
                    e.preventDefault();
                    $(".content").mCustomScrollbar("scrollTo", $(this).attr("href"));
                });

            });
        })(jQuery);
    </script>
{% endblock %}


{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <h1 style="color:red;font-size:20px;font-weight:bold;text-align:center;">
                博客管理后台
            </h1>
            <br>
            <p>商城管理采用Django2.0.7 + Python3.7.0开发，存储数据库为关系型数据库Mysql</p>
            <br>
            <p>商城后台集中功能为：商品分类、商品图片、商品库存、用户管理、收货地址管理、留言管理、订单管理等模块</p>
        </div>
    </section>
{% endblock %}

blog/templates/back/login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>后台登录</title>
<meta name="author" content="DeathGhost" />
<link rel="stylesheet" type="text/css" href="/static/back/css/style.css" />
<style>
body{height:100%;background:#16a085;overflow:hidden;}
canvas{z-index:-1;position:absolute;}
</style>
<script src="/static/back/js/jquery.js"></script>
<script src="/static/back/js/verificationNumbers.js"></script>
<script src="/static/back/js/Particleground.js"></script>
<script>
$(document).ready(function() {
  //粒子背景特效
  $('body').particleground({
    dotColor: '#5cbdaa',
    lineColor: '#5cbdaa'
  });
  //验证码
  createCode();
  //测试提交，对接程序删除即可
  $(".submit_btn").click(function(){
	  location.href="index.html";
	  });
});
</script>
</head>
<body>
  <form action="" method="POST">
    <dl class="admin_login">
      <dt>
        <strong>博客后台管理系统</strong>
        <em>Management System</em>
      </dt>
      {{ error }}
      <dd class="user_icon">
        <input type="text" name='username' placeholder="账号" class="login_txtbx" />
      </dd>
      <dd class="pwd_icon">
        <input type="password" name='password' placeholder="密码" class="login_txtbx" />
      </dd>
      <dd>
        <input type="submit" value="立即登录" class="submit_btn" />
      </dd>
      <dd align="center">
        <a href="{{ url_for('back.register') }}">没有账号，立即注册</a>
      </dd>
      <dd>
        <p>© 2015-2016 DeathGhost 版权所有</p>
        <p>陕B2-20080224-1</p>
      </dd>
    </dl>
  </form>
</body>
</html>

blog/templates/back/register.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>后台登录</title>
  <meta name="author" content="DeathGhost" />
  <link rel="stylesheet" type="text/css" href="/static/back/css/style.css" />
  <style>
    body {
      height: 100%;
      background: #16a085;
      overflow: hidden;
    }

    canvas {
      z-index: -1;
      position: absolute;
    }
  </style>
  <script src="/static/back/js/jquery.js"></script>
  <script src="/static/back/js/verificationNumbers.js"></script>
  <script src="/static/back/js/Particleground.js"></script>
  <script>
    $(document).ready(function () {
      //粒子背景特效
      $('body').particleground({
        dotColor: '#5cbdaa',
        lineColor: '#5cbdaa'
      });
      //验证码
      createCode();
      //测试提交，对接程序删除即可
      $(".submit_btn").click(function () {
        location.href = "index.html";
      });
    });
  </script>
</head>

<body>
    <form action="" method="post">
      <dl class="admin_login">
        <dt>
          <strong>博客后台管理系统</strong>
          <em>Management System</em>
        </dt>
        {{ error }}
        <dd class="user_icon">
          <input type="text" name='username' placeholder="账号" class="login_txtbx" />
        </dd>
        <dd class="pwd_icon">
          <input type="password" name='password' placeholder="密码" class="login_txtbx" />
        </dd>
        <dd class="pwd_icon">
          <input type="password" name='password2' placeholder="确认密码" class="login_txtbx" />
        </dd>
        <dd>
          <input type="submit" value="立即注册" class="submit_btn" />
        </dd>
        <dd align="center">
          <a href="{{ url_for('back.login') }}">已注册账号，立即登录</a>
        </dd>
        <dd>
    
          <p>© 2015-2016 DeathGhost 版权所有</p>
          <p>陕B2-20080224-1</p>
        </dd>
      </dl>
    </form>
</body>

</html>